simulation.customer.groups=150

ticket.duration.ms=15000

pool.olympic.name=Olimpijski
pool.olympic.capacity=10
pool.recreational.name=Rekreacyjny
pool.recreational.capacity=5
pool.recreational.max.average.age=40
pool.paddling.name=Brodzik
pool.paddling.capacity=5

customer.names.file=customer_names.csv
customer.age.min=1
customer.age.max=70
customer.vip.chance.percent=5
customer.pampers.chance.percent=80

customer.swimming.time.min.ms=1000
customer.swimming.time.max.ms=5000
customer.wait.time.min.ms=500
customer.wait.time.max.ms=1500

center.capacity=40
gate.queue.capacity=5
gate.passage.time.ms=300

cashier.count=3
cashier.service.time.max.ms=2000
cashier.service.time.min.ms=500

service.interval.time.ms=30000
service.cleaning.time.ms=5000
